SUCCESS = 0
ERR_INTERNAL_ERROR = -1
ERR_INVALID_COMMAND = -2
ERR_INVALID_PARAM = -3
ERR_USER_NOT_EXIST = -4
ERR_FOLLOWEE_IS_USER = -5
WARN_ALREADY_FOLLOWED = 1
WARN_NOT_FOLLOWED = 2

TYPE_CHECK_IN = 0
TYPE_CHECK_OUT = 1
